language: r
r: devel
sudo: true
cache: packages
dist: trusty

warnings_are_errors: false

apt_packages:
  - qpdf
r_github_packages: hadley/devtools

before_install:
  - mkdir ~/.R && echo 'CXX11=g++ -std=c++11 -g -O2 -fPIC' > ~/.R/Makevars

script:
  - R CMD build . ${R_BUILD_ARGS}
  - R CMD check `ls -1t *.tar.gz | head -n 1` ${R_CHECK_ARGS}$
  
cran: http://cran.rstudio.com
